---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - pushprox_install
    - pushprox_configure
    - pushprox_run

- import_tasks: preflight.yml
  tags:
    - pushprox_install
    - pushprox_configure
    - pushprox_run

- import_tasks: install.yml
  become: true
  tags:
    - pushprox_install

- import_tasks: configure.yml
  become: true
  tags:
    - pushprox_configure

- name: Ensure pushprox-proxy is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: pushprox-proxy
    enabled: true
  tags:
    - pushprox_run
  when: pushprox_install_proxy|bool

- name: Ensure pushprox-client is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: pushprox-client
    enabled: true
  tags:
    - pushprox_run
  when: pushprox_install_client|bool
